module.exports = {
  semi: false,
  trailingComma: 'all',
  singleQuote: true,
  tabWidth: 2,
  printWidth: 80,
  arrowParens: 'always',
  bracketSpacing: false,
  jsxBracketSameLine: false,
  htmlWhitespaceSensitivity: 'css',
  insertPragma: false,
  requirePragma: false,
  jsxSingleQuote: false,
  useTabs: false,
}
