/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface MyInput {
        "autocomplete": boolean;
        "disabled": boolean;
        "isValid": boolean;
        "labelText": string;
        "maxLength"?: number;
        "name": string;
        "onlyNumbers": boolean;
        "preventReturn": boolean;
        "required": boolean;
        "typeText": string;
        "value": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMyInputElement extends Components.MyInput, HTMLStencilElement {
    }
    var HTMLMyInputElement: {
        prototype: HTMLMyInputElement;
        new (): HTMLMyInputElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "my-input": HTMLMyInputElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface MyInput {
        "autocomplete"?: boolean;
        "disabled"?: boolean;
        "isValid"?: boolean;
        "labelText"?: string;
        "maxLength"?: number;
        "name"?: string;
        "onChangeValue"?: (event: CustomEvent<string>) => void;
        "onFocusLost"?: (event: CustomEvent<any>) => void;
        "onlyNumbers"?: boolean;
        "preventReturn"?: boolean;
        "required"?: boolean;
        "typeText"?: string;
        "value"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "my-input": MyInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-input": LocalJSX.MyInput & JSXBase.HTMLAttributes<HTMLMyInputElement>;
        }
    }
}
